### ISSUE TITLE
Support lazy dependency injection

### ISSUE THREAD

**Issue by sunesimonsen** [One-com/dislocator#1]
I propose supporting simple lazy dependency injection on first retrieval. That would allow us to avoid creating wrappers for every instance we don't control the interface of. Furthermore it means that in most cases you can avoid things needing to lookup stuff explicitly and therefore avoid a dependency on the locator. I don't think this approach is dangerous as we can provide very good error messages when you look up things that can't be resolved. 

Here is an example of what I want to achieve:

``` js
var locator = require('dislocator');

function MyService(databaseClient) {
    this.databaseClient = databaseClient;
    this.config = null;
}

locator.register('my-service', function (locator) {
    var myService = new MyService(locator.get('database-client'));
    myService.configuration = locator.get('configuration');
    return myService;
});

// dependency injection when retrieved for the first time.
locator.register({
    name: 'my-service',
    args: ['database-client'], 
    properties: {
        configuration: 'configuration'
    }
}, MyService);

// if the properties and the things you want to inject has the same
// names, you can do the following.

locator.register({
    name: 'my-service',
    args: ['database-client'], 
    properties: ['configuration']
}, MyService);
```

**Comment by papandreou** [comment]
Should that then be the only way to register a service? For services that are already "lazy by nature" I think it'd be an annoying extra layer of indirection.

**Comment by sunesimonsen** [comment]
We agreed that you could achieve everything using the standard syntax as easily: 

``` js
locator.register('my-service', function (locator) {
    var myService = new MyService(locator.get('database-client'));
    myService.configuration = locator.get('configuration');
    return myService;
});
```

So I'll just close the issue.
