### ISSUE TITLE
Support locator events

### ISSUE THREAD

**Issue by sunesimonsen** [One-com/dislocator#7]
This will allow cross cutting concerns like starting to listen on for events when instances gets created.  

``` js
locator.on('register', function (descriptor) {
});

locator.on('creation', function (descriptor, instance) {
});

locator.on('unregister', function (descriptor, instance) {
});
```

**Comment by birkestroem** [comment]
Events is now emitted:
https://github.com/One-com/dislocator/blob/master/test/dislocator.spec.js#L28
https://github.com/One-com/dislocator/blob/master/test/dislocator.spec.js#L63
https://github.com/One-com/dislocator/blob/master/test/dislocator.spec.js#L104
